SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS useraccount;
CREATE SCHEMA useraccount;
USE useraccount;

CREATE TABLE users(
  user_id INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(30) NOT NULL,
  lastName VARCHAR(30) NOT NULL,
  email VARCHAR(60) NOT NULL,
  dob DATE NOT NULL,
  CONSTRAINT userid_pk PRIMARY KEY(user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE login(
  login_id INT NOT NULL AUTO_INCREMENT,
  userName VARCHAR(20) NOT NULL,
  password VARCHAR(50) NOT NULL,
  CONSTRAINT loginid_pk PRIMARY KEY(login_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE login ADD CONSTRAINT userid_fk FOREIGN KEY (login_id) REFERENCES users(user_id);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
